# NumPy Lesson

This notebook covers core NumPy concepts: array creation, attributes, arithmetic, indexing, broadcasting, shape manipulation, random generation, linear algebra, performance tips, interoperability, and exercises.

## 1. Introduction to NumPy
- Library for numerical computing
- Provides `ndarray` for efficient array operations
- Benefits: speed, memory efficiency, rich API

## 2. Creating Arrays

In [ ]:
!pip install numpy

In [2]:
import numpy as np

# From Python sequences
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

print(a)
print('')
print(b)

[1 2 3]

[[1 2]
 [3 4]]


In [3]:
ab = np.array([1,2,3,4,'name'])
abc = [1,2,3,4,'name']

abc, ab


([1, 2, 3, 4, 'name'], array(['1', '2', '3', '4', 'name'], dtype='<U21'))

In [4]:
# Create an array of zeros with shape (2, 3)
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# Create an array of ones with shape (3,)   
ones = np.ones((3,2), dtype=int)  # Specify dtype as int to create integer

ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [6]:
#Full arrays
full = np.full((2, 2), 7)
full

array([[7, 7],
       [7, 7]])

In [10]:
#Aranging arrays
ar = np.arange(1, 10, 2)
ar

array([1, 3, 5, 7, 9])

In [48]:
# Random numbers between 0 and 1    
data = np.random.rand(3, 8)
data


array([[0.26815804, 0.68662799, 0.4723243 , 0.17301919, 0.55764575,
        0.74659344, 0.83015615, 0.77686472],
       [0.15596228, 0.68525337, 0.49102198, 0.88477194, 0.09495865,
        0.67939614, 0.09577332, 0.81474273],
       [0.37182837, 0.53465843, 0.75619183, 0.24218143, 0.40564108,
        0.38835049, 0.50422197, 0.13963496]])

In [66]:
#Random Integers
random_int = np.random.randint(0, 20, (3,3))
random_int

array([[ 5,  2, 14],
       [ 1, 12, 13],
       [ 4,  3,  3]])

In [69]:
#Linear space
lin = np.linspace(0, 100, 11)

lin

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [12]:
#Identity matrix
identity = np.identity(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 3. Array Attributes

In [77]:
# Attributes of ndarray
arr = np.arange(12).reshape(6,2)
print(arr)


arr.shape

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


(6, 2)

In [78]:
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Dtype:", arr.dtype)

Shape: (6, 2)
Dimensions: 2
Size: 12
Dtype: int64


In [79]:

# Reshape and type conversion
reshaped = arr.reshape(4, 3)
floats = arr.astype(str)
reshaped, floats

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([['0', '1'],
        ['2', '3'],
        ['4', '5'],
        ['6', '7'],
        ['8', '9'],
        ['10', '11']], dtype='<U21'))

## 4. Basic Arithmetic and Universal Functions (ufuncs)

In [81]:
# Element-wise operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x, y

(array([1, 2, 3]), array([4, 5, 6]))

In [89]:
print("Add:", x + y)
print("Multiply:", x * y)
print("Power:", x ** 2)

x/2

Add: [5 7 9]
Multiply: [ 4 10 18]
Power: [1 4 9]


array([0.5, 1. , 1.5])

In [88]:
# Universal functions
print("Sqrt:", np.sqrt(x))
print("Exp:", np.exp(x))
print("Max:", np.maximum(x, y))

Sqrt: [1.         1.41421356 1.73205081]
Exp: [ 2.71828183  7.3890561  20.08553692]
Max: [4 5 6]


In [19]:
# Aggregations
data = np.random.rand(3, 4)
data

array([[0.99448661, 0.283363  , 0.68631898, 0.3837161 ],
       [0.49204629, 0.95085463, 0.49931461, 0.41509703],
       [0.90553117, 0.4424953 , 0.89860757, 0.26205227]])

In [20]:
print("Sum:", data.sum())
print("Mean:", data.mean())
print("Std:", data.std())

Sum: 7.213883560124264
Mean: 0.6011569633436887
Std: 0.2599205178911514


## 5. Indexing, Slicing, and Iteration

In [21]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
arr[:,0:1] # (rows, columns)

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [23]:
# Slicing
print("Row 1:", arr[1])
print("Column 2:", arr[:, 2])
print("Subarray:", arr[1:3, 1:3])


Row 1: [4 5 6 7]
Column 2: [ 2  6 10 14]
Subarray: [[ 5  6]
 [ 9 10]]


## 6. Broadcasting
- Align dimensions
- Expand size-1 dimensions

Example: add 1D to each row of 2D array

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print("Broadcasted sum:", a + b)

Broadcasted sum: [[11 22 33]
 [14 25 36]]


## 7. Shape Manipulation and Combining Arrays

In [25]:
# Reshaping and transposing
arr = np.arange(6)
print("Original:", arr)
print("Reshaped 2x3:", arr.reshape(2, 3))

Original: [0 1 2 3 4 5]
Reshaped 2x3: [[0 1 2]
 [3 4 5]]


In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# i. Dot product
dot_product = np.dot(a, b)
print("Dot product:", dot_product)



Dot product: 32


In [30]:

# ii. Matrix multiplication
a_2d = a.reshape(3, 1)
b_2d = b.reshape(1, 3)
a_2d, b_2d


(array([[1],
        [2],
        [3]]),
 array([[4, 5, 6]]))

In [31]:
mat_mult = a_2d @ b_2d
print("Matrix multiplication result:\n", mat_mult)

Matrix multiplication result:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [32]:
arr = np.arange(25).reshape(5, 5)
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
border_elements = np.concatenate((
    arr[0, :],        # Top row
    arr[1:-1, 0],     # Left column (excluding corners)
    arr[1:-1, -1],    # Right column (excluding corners)
    arr[-1, :]        # Bottom row
))
print("Border elements:", border_elements)

Border elements: [ 0  1  2  3  4  5 10 15  9 14 19 20 21 22 23 24]
